services:
  nodejs:
    build: .
    container_name: nodejs-2
    ports:
      - 3002:3002
    restart: unless-stopped
    tty: true
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
